binary_build_commands: make build
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.21-openshift-4.16
images:
- dockerfile_path: Dockerfile
  from: ubi_minimal
  to: topolvm
promotion:
  to:
  - namespace: lvms
    tag: latest
    tag_by_commit: true
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: topolvm-conformance
  steps:
    cluster_profile: aws
    workflow: lvms-topolvm-conformance
zz_generated_metadata:
  branch: main
  org: openshift
  repo: topolvm
